# Generated by Django 3.2.20 on 2023-10-08 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RealState', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=2000)),
                ('address', models.TextField(max_length=300)),
                ('phone_number', models.CharField(max_length=10)),
                ('Year_of_Construction', models.DecimalField(decimal_places=0, max_digits=4)),
                ('Number_of_rooms', models.DecimalField(decimal_places=0, max_digits=2)),
                ('Ground_Area', models.FloatField()),
                ('Features', models.TextField(max_length=4000)),
                ('Total_Price', models.DecimalField(decimal_places=0, max_digits=14)),
                ('Price_per_meter', models.DecimalField(decimal_places=0, max_digits=14)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RealState.area')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Property_Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RealState.property')),
            ],
        ),
    ]
