# Generated by Django 3.2.20 on 2023-10-28 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RealState', '0005_alter_property_builder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='Builder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='builder', to='RealState.builder'),
        ),
    ]
