# Generated by Django 3.2.20 on 2023-10-28 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RealState', '0006_alter_property_builder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property_images',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='RealState.property'),
        ),
    ]
