# Generated by Django 4.2.9 on 2024-02-12 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("RealState", "0008_alter_property_images_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="Bathroom",
            field=models.DecimalField(decimal_places=0, default=0, max_digits=2),
        ),
    ]
